[".oh-my-zsh"]
    type = "git-repo"
    url = "https://github.com/ohmyzsh/ohmyzsh.git"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".oh-my-zsh-custom/plugins/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".oh-my-zsh-custom/plugins/zsh-history-substring-search"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-history-substring-search.git"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".oh-my-zsh-custom/themes/powerlevel10k"]
    type = "git-repo"
    url = "https://github.com/romkatv/powerlevel10k.git"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".config/tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".config/wezterm/colors/dracula"]
    type = "git-repo"
    url = "https://github.com/dracula/wezterm.git"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
